[book]
title = "Gitea Codespace 设计文档"
authors = ["Gitea"]
language = "zh-CN"

[build]
build-dir = "book"

[output.html]
site-url = "/gitea-dev/"
git-repository-url = "https://github.com/ExplodingDragon/gitea-dev"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 1

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
