[book]
title = "Gitea Codespace 设计文档"
authors = ["Gitea"]
language = "zh-CN"

[build]
build-dir = "book"

[output.html]
site-url = "/gitea-dev/"
git-repository-url = "https://github.com/ExplodingDragon/gitea-dev"

[output.html.fold]
enable = true
level = 1
